# כתובת ה-JDBC הנקייה של Neopp-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require
# אם המשתנה NEON_DB_URL לא נמצא, Spring ישתמש בכתובת שרשומה אחרי הנקודתיים
spring.datasource.url=${NEON_DB_URL:jdbc:postgresql://ep-lingering-shadow-adsebopp-pooler.c-2.us-east-1.aws.neon.tech/neondb}?sslmode=require
spring.datasource.username=${NEON_DB_USER}
spring.datasource.password=${NEON_DB_PASS}



# פרטי הגישה של השרת


# הגדרת הדרייבר (השארנו ללא שורת ה-database-platform הבעייתית)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# הגדרות Hibernate וריצה
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# פורט השרת
server.port=8080
